<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Akademik</name>
   <tag></tag>
   <elementGuidId>c74a7651-baee-4205-8f1f-ce6b5f04c0b7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//li[@id='menu-item-745']/a)[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#mobile_menu > #menu-item-745 > a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>2186f3ff-bc68-46ff-8411-4b51b577cc16</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>d21fc19d-89ec-4732-bc6e-09e78bcfe6eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Akademik</value>
      <webElementGuid>d2a362d4-0d11-4273-ba21-d458ef013644</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mobile_menu&quot;)/li[@id=&quot;menu-item-745&quot;]/a[1]</value>
      <webElementGuid>b67ba6ba-c0b4-4296-aa38-3469986374e2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//li[@id='menu-item-745']/a)[2]</value>
      <webElementGuid>2723a178-e892-422f-89b8-90a69d1941e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'Akademik')])[4]</value>
      <webElementGuid>6cdfb174-1318-4262-b7ef-2837335e4954</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Identitas Visual'])[2]/following::a[1]</value>
      <webElementGuid>684224dd-98ac-454d-b5ea-5acd222b2160</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Keluarga Alumni Duta Wacana (KADUWA)'])[2]/following::a[2]</value>
      <webElementGuid>baea508c-6fbe-4ba2-bde6-e53ee8da6954</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sarjana Filsafat Keilahian'])[2]/preceding::a[3]</value>
      <webElementGuid>c5a9edd9-1f20-4009-94c5-fd34a5e9bcb0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Magister Filsafat Keilahian'])[2]/preceding::a[5]</value>
      <webElementGuid>927b66c8-8fa9-47d5-b889-b697bda993bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '#')])[25]</value>
      <webElementGuid>063e23ca-e246-4c8b-a211-60262c1d0f8a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/ul/li[2]/a</value>
      <webElementGuid>b30ce2b2-ac7b-48ad-a6ea-aee1714eb480</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#' and (text() = 'Akademik' or . = 'Akademik')]</value>
      <webElementGuid>563da06e-10ca-409a-9f3f-4f4f42d41d42</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
