<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Fakultas Teknologi Informasi</name>
   <tag></tag>
   <elementGuidId>45486d1b-8daa-4fac-98ac-d79a818d1c77</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//li[@id='menu-item-798']/a)[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#mobile_menu > #menu-item-745 > ul.sub-menu > #menu-item-798 > a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>7e72e957-d003-416f-af88-51f0d45adcd6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>cf9ab2fb-a240-49f6-8e61-073d07297c9a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Fakultas Teknologi Informasi</value>
      <webElementGuid>5b0cfe2e-7eb8-436a-a41e-6d0c21fd315a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mobile_menu&quot;)/li[@id=&quot;menu-item-745&quot;]/ul[@class=&quot;sub-menu&quot;]/li[@id=&quot;menu-item-798&quot;]/a[1]</value>
      <webElementGuid>83fb3267-1eb0-42eb-bd8c-64390b53722f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//li[@id='menu-item-798']/a)[2]</value>
      <webElementGuid>e519a582-bd6f-4df3-bbed-b0bc23a8e64e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'Fakultas Teknologi Informasi')])[2]</value>
      <webElementGuid>86fc9f92-240a-4151-9c51-9a0b66d89407</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Magister Manajemen'])[2]/following::a[1]</value>
      <webElementGuid>658859e4-3c9f-4c99-8c08-1d81118b449d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Akuntansi'])[2]/following::a[3]</value>
      <webElementGuid>17b24677-898a-4992-bdec-b6c62bc5cb6d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Informatika'])[2]/preceding::a[2]</value>
      <webElementGuid>ea9ab648-5428-4232-9d5c-ce785fe2e4fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sistem Informasi'])[2]/preceding::a[3]</value>
      <webElementGuid>e4139aed-1454-47a5-bec2-9e8aba8d3960</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '#')])[38]</value>
      <webElementGuid>974afcc0-2b57-455b-af84-80bb128eb478</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/ul/li[2]/ul/li[5]/a</value>
      <webElementGuid>d9bb2f92-caa6-4a2d-86e6-469f022b099d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#' and (text() = 'Fakultas Teknologi Informasi' or . = 'Fakultas Teknologi Informasi')]</value>
      <webElementGuid>73e456ee-6316-4221-839f-80fb24c2e127</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
