<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Pilih Laman_mobile_menu_bar mobile_men_24b656</name>
   <tag></tag>
   <elementGuidId>0fb05783-81eb-489e-8faa-ca83767a56e6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='et_mobile_nav_menu']/div/span[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.mobile_menu_bar.mobile_menu_bar_toggle</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>bbfa588e-7164-4d3c-9f1e-8b38b8d0da46</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mobile_menu_bar mobile_menu_bar_toggle</value>
      <webElementGuid>bee8fce7-61ba-4966-94b8-731203f3cd93</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;et_mobile_nav_menu&quot;)/div[@class=&quot;mobile_nav closed&quot;]/span[@class=&quot;mobile_menu_bar mobile_menu_bar_toggle&quot;]</value>
      <webElementGuid>d3c69326-367a-4dd6-9fb6-5dae4ba904ea</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='et_mobile_nav_menu']/div/span[2]</value>
      <webElementGuid>58d3d5b5-eb7d-49a7-b0a7-f95b223c4894</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[2]</value>
      <webElementGuid>90182a7e-6c57-417a-b808-2906d02e0d9b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
