<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_DosenSistem Informasi</name>
   <tag></tag>
   <elementGuidId>3eb7a9f7-e101-4bf4-a982-10c18336c2ae</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='et-boc']/div/div/div[2]/div/div/div/p</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>p</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>76f3c75e-9960-4606-a9bc-21170bcaa0c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Dosen Sistem Informasi</value>
      <webElementGuid>ceb1b1d1-195e-43b2-b13f-59743736b7c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;et-boc&quot;)/div[@class=&quot;et_builder_inner_content et_pb_gutters3&quot;]/div[@class=&quot;et_pb_section et_pb_section_0 et_section_regular&quot;]/div[@class=&quot;et_pb_row et_pb_row_1&quot;]/div[@class=&quot;et_pb_column et_pb_column_2_3 et_pb_column_1    et_pb_css_mix_blend_mode_passthrough&quot;]/div[@class=&quot;et_pb_module et_pb_text et_pb_text_0 et_pb_bg_layout_light  et_pb_text_align_left&quot;]/div[@class=&quot;et_pb_text_inner&quot;]/p[1]</value>
      <webElementGuid>f0deecbd-4aab-41f5-8fb6-630488ce4952</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='et-boc']/div/div/div[2]/div/div/div/p</value>
      <webElementGuid>3f300ff0-2396-4e92-bbba-a271a6d069d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Wakil Dekan II Fakultas Teknologi Informasi'])[1]/following::p[1]</value>
      <webElementGuid>06920ea4-5e0e-4f55-94e6-4b00cf6d4e57</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Argo Wibowo, S.T., MT'])[2]/following::p[1]</value>
      <webElementGuid>8a99dcd3-b48e-48a9-948a-6967e7aed83b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p</value>
      <webElementGuid>e5ee04a3-23ae-457e-a9af-13890dfe78d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = 'Dosen Sistem Informasi' or . = 'Dosen Sistem Informasi')]</value>
      <webElementGuid>06e0f63a-e5f4-41af-ac68-0c38cebff3e6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
